### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by theonelucas** [rtman/react-datatables#1]
Hi, I just wanted to congratulate you for the effort of porting the amazing DataTables lib to React! Also, I would like to ask you, will this port be jQuery free? It would be amazing if this was the case, I'm willing to help make that a reality!

**Comment by rtman** [comment]
@theonelucas Hey sorry about the late reply. 
Thanks! 
No I don't have any intention to port it from jquery at this time. Although that would be great if it happened! Quite frankly it works pretty well as is in react so I am going to just go ahead and use it.

**Comment by theonelucas** [comment]
Ok then, but I will keep watching the repo for issues, thanks
